#!/usr/bin/env bash

executed_file=$(readlink -f ${BASH_SOURCE[0]})
script_dir=$(dirname ${executed_file})

force_wayland=true

args=""
env=""

if $force_wayland && [[ "$XDG_SESSION_TYPE" = "wayland" ]]; then
  args="-platform wayland"
  env="QT_WAYLAND_SHELL_INTEGRATION=wl-shell"
fi

env="$env __GL_SYNC_TO_VBLANK=1 QML_FORCE_THREADED_RENDERER=1"

export $env
${script_dir}/artriculate $args
