#!/usr/bin/env bash

executed_file=$(readlink -f ${BASH_SOURCE[0]})
script_dir=$(dirname ${executed_file})

cmd=${script_dir}/artriculate-bin

args="$@"

if [[ "$QT_QPA_PLATFORM" != "eglfs" ]]; then
    unset QT_QPA_PLATFORM
fi

echo "Running cmd: $cmd with args: $args"
$cmd $args
