#!/usr/bin/env bash

executed_file=$(readlink -f ${BASH_SOURCE[0]})
script_dir=$(dirname ${executed_file})

force_wayland=true

bin_name=artriculate-bin
dev_name=${script_dir}/src/${bin_name}
if [[ -x ${dev_name} ]]; then
  cmd=${dev_name}
else
  cmd=${script_dir}/${bin_name}
fi

args=""
env=""

if $force_wayland && [[ "$XDG_SESSION_TYPE" = "wayland" ]]; then
  args="-platform wayland"
fi

env="$env __GL_SYNC_TO_VBLANK=1 QML_FORCE_THREADED_RENDERER=1"

export $env
$cmd $args
